### ISSUE TITLE
profiler issue when training with 64 or more GPUs

### ISSUE THREAD

**Issue by tianyu-l** [pytorch/torchtitan#266]
Issues happened at the profiler steps frequently, under the disguise of other problems such as all-reduce timeouts.

**Comment by tianyu-l** [comment]
We tried inserting a `torch.distributed.barrier()` right after trace dumping. However, it doesn't seem to resolve the issue. In fact, now the timeout happens at the all-reduce which the barrier itself issues (with 100 seconds timeout).

It is confusing that dumping on all ranks takes less than 25 seconds, and it seems all ranks have joined the barrier, and all ranks seems to have timed out.

Reopen to track this issue.

**Comment by tianyu-l** [comment]
Investigated offline with @wconstab, it seems not all ranks finished trace dumping and got stuck, thus causing timeout. We wondered if it was caused by unstable mounted storage write. I'll switch to "dumping to local disk during training -> cp to mounted storage after training" and see if it helps.

**Comment by wconstab** [comment]
This is also a case where our tooling for desync debug needs to improve.  It should be very easy/quick to learn that 32/64 ranks did not join the barrier and that's the reason for the timeout, but it still requires some head-scratching today to get to that conclusion.  cc @c-p-i-o

**Comment by wconstab** [comment]
oh - in this case, the users (us) didn't even try using the flight recorder. we just looked at the logs carefully and determined that only 32 ranks printed a log that was right before the barrier call, so then we realized the other 32 were missing from the barrier.  or something like that.

my point is that in general, we want the timeout message to say something nice and helpful like "these specific ranks didn't join", instead of the opaque message we get today which is just that some collective timed out

**Comment by tianyu-l** [comment]
update: the issue has been figured out -- it's because the profiling dumping step taking too much time than reasonable. It only takes 0.5 seconds for 70B model to dump (~80MB trace per rank) to local disk, but was taking ~1000 seconds for the mounted storage.
