### ISSUE TITLE
Is torch compile not supposed to be applied after FSDP?

### ISSUE THREAD

**Issue by mayank31398** [pytorch/torchtitan#472]
https://github.com/pytorch/torchtitan/blob/0f70507f1350679428ea64f90bc5a7db17b9c103/torchtitan/parallelisms/parallelize_llama.py#L557-L564

**Comment by yf225** [comment]
yeah I think compile should be applied after FSDP. would be curious the blockers cc. @tianyu-l @wanchaol

**Comment by mayank31398** [comment]
yeah, its working in my tests but I am not using torchtitan.
though the code flow is equivalent.

**Comment by mayank31398** [comment]
also, I have same question about the order of PP and FSDP.
Can I apply FSDP after PipelineStage?

**Comment by wanchaol** [comment]
hmmm yes I think ideally compile could be applied after FSDP, however there're a couple of reasons on why we didn't do that:

1. apply compile before FSDP allow compile only works on the non-FSDP logic, instead of trying to graph break on the FSDP logic. Even though the latter approach work, this is just simpler and could avoid non-necessary graph breaks.
2. apply compile before FSDP could possibly make some of our newer compile time improvements be applied easier (i.e `inline_inbuilt_nn_modules`). We might need check and see if this could be used if we apply compile after FSDP.

For those reasons, I think even though apply compile before/after FSDP could work, we are currently applying compile before FSDP.

**Comment by mayank31398** [comment]
also, I have same question about the order of PP and FSDP.
Can I apply FSDP after PipelineStage?
