### ISSUE TITLE
regarding torch.compile support

### ISSUE THREAD

**Issue by jason718** [pytorch/torchtitan#479]
in coming soon, there is an item called `torch.compile support`. I'm wondering if we simply call torch.compile once to wrap the entire model, will that be enough? What's the reason we want to do something more fine-grained and customized?

**Comment by tianyu-l** [comment]
The main reason to call `torch.compile` for each `TransformerBlock` is due to the feature `torch._dynamo.config.inline_inbuilt_nn_modules=True` from compiler. Because `TransformerBlock` has the same pattern repeated multiple times, ideally compiler should only compile once. Currently this is only available if we compile each `TransformerBlock` individually.

You can still compile the whole model in most cases (there might appear bugs as compiler is under heavy development), but compiling time would be longer.

**Comment by jason718** [comment]
Thanks for explaining!
