### ISSUE TITLE
How to train using bfloat16?

### ISSUE THREAD

**Issue by zyushun** [pytorch/torchtitan#528]
Hi! I have a quick question: how to train using bfloat16? I found the default setting using fp32. 

I changed ''data_parallel_degree"  to 4 (my number of GPUs) but still did not use  bfloat16.

Thanks in advance!

**Comment by lessw2020** [comment]
Hi @zyushun, 
The default training for titan is fsdp2 with mixed precision and bfloat16 for parameters.
You can control the dtype in toml or command line via this config setting:
https://github.com/pytorch/torchtitan/blob/81c555f8bd6791ccd575a52bdcaaf816f4de7ee6/torchtitan/config_manager.py#L329
Currently it is set to bfloat16 as default. The number of gpus will not change the param dtype.
Can you clarify why you believe your training is in fp32? 
Note that checkpoints will always save out as fp32 for portability.

**Comment by zyushun** [comment]
Hi @lessw2020 ! Thanks a lot for the clarification.

I observe fp32 when I print the type of params in the optimizer (I used Adam-mini in my case):

```
    @torch.no_grad()
    def step(self, closure=None):
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()
        for group in self.param_groups:
            beta1 = group["beta1"]
            beta2 = group["beta2"]
            lr = group["lr"]
            name = group["name"]
            eps = group["eps"]

            for p in group["params"]:
                print(f'name = {name}, dtype = {p.dtype}')
                state = self.state[p]
```

and I got the following results:

```
[rank0]:======>>>>> Using Adam-mini optimizer
[rank0]:name = tok_embeddings.weight, dtype = torch.float32
[rank0]:name = layers.0._checkpoint_wrapped_module.attention.wq.weight, dtype = torch.float32
[rank0]:name = layers.0._checkpoint_wrapped_module.attention.wk.weight, dtype = torch.float32
[rank0]:name = layers.0._checkpoint_wrapped_module.attention.wv.weight, dtype = torch.float32
[rank0]:name = layers.0._checkpoint_wrapped_module.attention.wo.weight, dtype = torch.float32
```
I was using the default setting as you suggested, so it is supposed to be mixed precision (bfloat16 for parameters) as you said. But I am not sure why the print suggested that I am using fp32... :(

**Comment by lessw2020** [comment]
Hi @zyushun!
Ah I see - so two parts then:
a - for optimizer states, those are completely controlled by the optimizer itself and  their states function independently of fsdp and the param dtype.  Thus you, as an optimizer writer, can keep your states in any dtype you would like (no guarantee it will work overall, but point is the control is in the optimizer hands). 
b - for the second check on your local weights, ala wq.weight, etc. you are now viewing the locally owned master weights (which are fp32).  As training proceeds, the all_gather to collect the weights will take place in bf16 (assuming the default fsdp param dtype is bf16) and those locally owned weights will be temp downcast to bf16 as part of that, and then the 'working weights' for each section will all proceed in bf16...from there the master weights will be updated by the optimizer (which generically will have fp32 states). 

Let me cc @awgu  to make sure I'm clarifying everything correctly above, but the net is that the local weights owned by each gpu are the master weights and will remain in fp32, but the actual working weights are downcast to the working dtype, and model forward and backward will all happen in the dtype speced in the first dtype config for fsdp params I sent above - in this case bf16.
Hope that helps!

**Comment by awgu** [comment]
Like @lessw2020  said, the default in torchtitan is bf16/fp32 mixed precision.

The sharded parameters (sharded by FSDP) are in fp32. This is determined by the dtype that the model is initialized in. When a module is passed to FSDP, FSDP shards the parameters on the module and does not change their dtype.

For example, in torchtitan where we use a meta-device initialization flow (init on meta device, parallelize with FSDP, move parallelized model to CUDA):
https://github.com/pytorch/torchtitan/blob/81c555f8bd6791ccd575a52bdcaaf816f4de7ee6/train.py#L117-L118
https://github.com/pytorch/torchtitan/blob/81c555f8bd6791ccd575a52bdcaaf816f4de7ee6/train.py#L159
https://github.com/pytorch/torchtitan/blob/81c555f8bd6791ccd575a52bdcaaf816f4de7ee6/train.py#L163
then, if you wanted the model to be initialized in bf16, then you can do something like:
```
torch.set_default_dtype(torch.bfloat16)
model.to_empty(device=init_device) 
torch.set_default_dtype(torch.float32)  # restore original fp32 default
```

These fp32 sharded parameters are returned from `model.parameters()` after this point. Hence, these are the parameters passed to the optimizer, which is conventionally initialized after the parallelization and materialization onto CUDA.

Note that for LLM pretraining, we typically use fp32 sharded parameters because the optimizer step/states prefer being in fp32 for convergence.

FSDP's `MixedPrecisionPolicy`'s `param_dtype` controls the dtype used for forward/backward computation -- i.e. the unsharded parameter dtype. For example, if you pass `param_dtype=torch.bfloat16`, then FSDP will cast the fp32 sharded parameters to bf16 right before all-gather, all-gather in bf16, and then use the all-gathered/unsharded fp32 parameters for forward (and similarly for backward).

**Comment by zyushun** [comment]
Thanks @lessw2020 @awgu for the detailed clarification! Great lecture and I now understand 💯
