### ISSUE TITLE
HSDP IB Issues

### ISSUE THREAD

**Issue by karan-dalal** [pytorch/torchtitan#633]
I'm attempting to run HSDP on 2 nodes each with 2 A100s. I'm using a script similar to `multinode_trainer.slurm`

Currently, I've set the following:
```
export NCCL_DEBUG=WARN
export NCCL_SOCKET_IFNAME="eth0,en,eth,em,bond"
export NCCL_BUFFSIZE=2097152
```

When I train my model with only FSDP (`data_parallel_shard_degree=4`), I'm able to run. However, when I enable HSDP by setting `data_parallel_replicate_degree=2`, I get the following error followed by a Python seg fault:
```
 [0] misc/ibvwrap.cc:169 NCCL WARN Call to ibv_reg_mr_iova2 failed with error Cannot allocate memory
```

If I additionally set `export NCCL_IB_DISABLE=1` then I am able to train. However, I've read online that this can slow down communication time significantly. I tried disabling for FSDP and noticed the training time double.

Is this an issue with my IB setup? Why might it only happen for HSDP, but not FSDP? Thanks!

**Comment by tianyu-l** [comment]
cc: @lessw2020 @kwen2501 @fegin

**Comment by lessw2020** [comment]
Hi @karan-dalal,
I can offer a likely solution here but I don't know specifically why HSDP would trigger it. 
Regardless, you need to increase the pinned memory available for Nvidia Infiniband
via /etc/security/limits.conf configuration file as referenced in
https://docs.nvidia.com/deeplearning/nccl/archives/nccl_2143/user-guide/docs/troubleshooting.html#infiniband
Make sure you reboot after the changes.  

"Modifying /etc/security/limits.conf is the long term solution so that limits are good on the next reboot. Reboot and ensure ulimit -l is indeed showing the right values, even within mpirun.
You can ensure that by running mpirun <mpirun args> <some script printing ulimit -l>"
https://github.com/NVIDIA/nccl-tests/issues/206

Once you increase the available memory, then you should be able to train with HSDP and at fast speed since you will be using Infiniband.
Please let us know if this resolves the issue for you!

**Comment by karan-dalal** [comment]
Hi @lessw2020, it seems this was already enabled on my cluster. It did not solve the issue. 

I've had another issue on a separate cluster where FSDP runs, but HSDP just hangs.

**Comment by fegin** [comment]
Can you check the CUDA memory usage?

**Comment by lessw2020** [comment]
Hi @karan-dalal  - thanks for the update, though sorry to hear things have not been resolved.
Similar to @fegin's comment above, I have a general question here:
a - what model size are you training?  Can you try and run this same setup but using the debug model, b/c at the moment it seems you are going from 1 model sharded by 4 gpus with FSDP, and then for HSDP, you are shrinking the effective model sharding size to fit it on only 2 gpus. 
Thus, wondering if you could do a quick test of repeating this but with the debug model (which is tiny) and let's see if that is able to run with HSDP.

**Comment by karan-dalal** [comment]
Hi @lessw2020, sorry for the late response. I was training a 125M model, which was able to train on 2 GPUs. 

I've moved to a different cluster, in which using FSDP is enough. I'll go ahead and close this issue for now, and reopen it if I experience it again in the future. Thanks!
